[build] 
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.54.0" # if old, use format: 0.53 (no trailing zero)
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"