---
title: "News"
---

- **11 February 2026**: [Paper](https://read.dukeupress.edu/demography/article/doi/10.1215/00703370-12464628/407367/The-Limits-of-Predicting-Individual-Level) in *Demography* on the limits of predicting individual-level mortality, led by the fabulous past students of the MPIDR Summer Incubator Program. 
- **28 January 2026**: The next [Formal Demography Working Group](https://formaldemography.github.io/working_group/) is 5 Febuary at 10am ET.
- **21 January 2026**: The [Toronto Population Network](https://isi.utoronto.ca/initiative/population-network/) Seminar Series is happening this semester!
- **24 October 2025**: The [Toronto Population Network](https://www.eventbrite.ca/e/toronto-population-network-tickets-1652952438239) is holding its first event on 6 November.
- **15 September 2025**: Excited to be involved with the new [Bayesian Social Sciences Section of ISBA](https://bss-isba.github.io/).
- **1 April 2025**: Honored to receive the [2025 IUSSP Early Career Award](https://iussp.org/en/2025-iussp-early-career-awards-ceremony) for the North American region.
- **8 March 2025**: [Paper](https://www.thelancet.com/journals/langlo/article/PIIS2214-109X(24)00560-6/fulltext) in *The Lancet Global Health* on the leading causes of maternal death.
- **14 January 2025**: [Paper](https://www.demographic-research.org/articles/volume/52/3) in *Demographic Research* led by Ameer Dharamshi on estimating subnational mortality jointly for multiple populations.
