---
title: "Tenured"
author: "Monica Alexander"
date: "2024-06-24"
output: html_document
---

I recently found out that I got tenure at the University of Toronto and as of 1 July I will be an Associate Professor in Statistical Sciences and Sociology. About six years ago [I wrote a little post](https://www.monicaalexander.com/posts/2018-23-05-demog_phd/) about getting my PhD, which turned into an unsolicited (and frankly, wildly misplaced) advice column. Six years on I am much more aware that I don't have any useful advice to give, but nevertheless wanted to share some thoughts to commemorate this milestone[^1], and to share my gratitude. 

[^1]: The first commemoration of this news was a McFlurry. The second was a nice bottle of champagne. 

# What do I do and how did I get here

Despite being housed in both a statistics and sociology department, I consider myself a card-carrying demographer. My undergrad degree was mostly statistics and chemistry[^2], and after working in the lab at a salmon factory, and an ill-advised stint at a bank, I did a Masters in Social Research at ANU. I took as many demography courses as a I could and was very into demographic methods.[^3] I was lucky enough to end up in the demography PhD program at Berkeley[^4], during which time I also completed an MA in statistics. 

My research interests are, to put it mildly, all over the place[^5], with the tenuous link of the estimation of demographic and population phenomena that are, for some reason or another, difficult to quantify. A large piece of this research relies on using Bayesian methods to estimate population outcomes where the data that exist are sparse or unreliable. I would probably call myself a statistical demographer[^6], but draw on formal demographic methods in much of my work. Substantively, I'm most interested in the dynamics of mortality disparities (and how best to quantify these); and early-life mortality, including the connection of fetal, infant and maternal outcomes. 

My interests stem from a wide variety of influences during the course of my career, resulting in the mish-mash frankenstein of interdisciplinary thoughts that make up my Google Scholar page. The formative experience at Berkeley was shaped by many people, but three in particular are worth singling out. My PhD advisor, [Josh Goldstein](https://jrgoldstein.com/), has an incredible knack of thinking about problems in a completely unique way, and my broad interests across many areas of demography are certainly influenced by his holistic approach to research questions. [Ken Wachter](https://statistics.berkeley.edu/people/ken-wachter) has a meticulous knowledge of demography and statistics --- and the intersection of both fields --- and it was a privilege to have him as a mentor. Finally, [Leontine Alkema](https://leontinealkema.github.io/alkema_lab/), who visited Berkeley in Spring 2014, re-introduced me to Bayesian methods, and perhaps more importantly, supported me through the early stages of my career and showed me what it was to be a strong mentor for women in a field that continues to be dominated by men. 

[^2]: This was after a brief stint in geology, which I promptly gave up because I couldn't keep up with all the drinking. I majored in math and chemistry, the latter to mostly prove to myself I could get through it (my god, the lab hours), and then did an honors year in statistics. That year I first learnt about Bayesian inference, thanks to my advisor [Simon Wotherspoon](https://scholar.google.com.au/citations?user=pa9IO3UAAAAJ&hl=en). 
[^3]: This was my first exposure to [Preston, Heuveline and Guillot](https://books.google.com/books/about/Demography.html?id=xlv2H6LpNAwC)
[^4]: After some not-so-subtle encouragement from Rohan to take the GRE and apply
[^5]: Worried about penning a coherent research narrative? Don't worry, if I can, anyone can!
[^6]: [Leontine Alkema](https://leontinealkema.github.io/alkema_lab/) wrote an insightful [set of reflections](https://drive.google.com/file/d/120QQZBgGPnOtBuw2BAC7MyNmg9DxBxSh/view) about statistical demography after being promoted to Full Professor. 



# (Social) capital gains

Part of what makes this job so great is the people, and the ability to have influence and impact beyond just writing research papers. The social impact and community building aspect of this job is something I have found surprisingly fulfilling.[^7] I feel as though in demography, we are particularly lucky to have such a vibrant, supportive community, which I have benefited from greatly. Indeed, I'm writing this while sitting at MPIDR, where I'm part of the [summer incubator program](https://www.demogr.mpg.de/en/research_6120/digital_and_computational_demography_zagheni_11666/population_and_social_data_science_summer_incubator_program_11935), and during my stay I'm overlapping with someone I met in 2015 during a workshop, someone who gave a talk at our Formal Demography Working Group, and someone I did my PhD with. It's a small community, but ties are strong, and collaborations are rich.[^8]

Another point I want to make here is about teaching. This often comes secondary to research (by virtue of the system), and it can be frustrating and time consuming, and we often like to complain about it.[^9] But the impact we have through teaching is usually far greater than research, the comments from students like 'you changed my mind about statistics' or 'I'm not scared of stats anymore' or 'I still use your notes' or 'This course helped me get a job' are the ones that mean the most. 

[^7]: Surprising given I'm an extroverted introvert, at best
[^8]: This is sounding a bit Hotel California, but like, in a good way
[^9]: Me included, if I never have to see a Piazza board again I'll be happy

# There's no formula

I promised this wouldn't be an advice column, and it won't be, because I don't have any good, useful, concrete advice to give. After we had our first baby, and we were still in the phase of bewilderment of having a newborn to care for --- the phase where almost every person and their dog felt the need to give us unsolicited advice about being a parent[^10] --- a friend gave me the best piece of advice: take everything with a grain of salt, just do what is best for you and your family, do what you have to; to get through it and stay sane. I feel as though there are parallels here to the tenure system. Ask questions, get feedback, listen to what others think and advise, but in the end, do what works for you, and what makes the research and the job more broadly most fulfilling. 

[^10]: Particularly, we found, if you're the mother; complete strangers would come up to me on the street to tell me my baby was too hot/ too cold / too big / too small

# It takes a village, and usually in academia we have to build that village ourselves

I am from Hobart, Tasmania, a small city centered around a river that will always be, for me, the most important place in the  world. But it's been more than 10 years since I lived in Australia, and almost 15 years since I've lived in Tasmania. In academia it's somewhat normalized to be a migrant: many of us have moved far away from home to study, for postdocs, for jobs. We normalize geographic flexibility, constraints being relaxed in preference for finding a job that is stable and fulfilling. But normalizing it doesn't mean it's easy. 

I am so grateful for the people in this community that I have somehow managed to find that offer support, guidance, and friendship. Ironically perhaps, though academic life is geographically transient, the people I am grateful for are attached to places I have passed through along this journey: Hobart, Canberra, Berkeley, Chicago, Amherst, Rostock, Toronto. There are too many people to name, and I feel as though if I tried I would inevitably miss people out. But you know who you are. Thank you. 

<!-- When I wrote the end-of-PhD post, I mentioned [Rohan](https://rohanalexander.com/) was the one who convinced me I could probably do a PhD in the US. Six years on, and he's the reason why I'm still here --- with every additional kid, there's an additional person in our household that he puts before himself; there's no real value that  -->


