---
title: "Music, statistics, and the appreciation of order and chaos"
author: "Monica Alexander"
date: "2025-12-10"
output: html_document
---

Recently my childhood piano teacher passed away. [Eric Mitchell, OAM](https://gnet.tgc.vic.edu.au/wiki/MITCHELL-Eric-G-OAM-1929) (or, Mr Mitchell as he always was to us) grew up in Victoria, Australia. He studied in Paris, where he met and married a baroness, and they eventually settled in Tasmania. I had piano lessons with Mr Mitchell from age 4 to 19. As two of my older brothers also had lessons with him, he was part of our lives for a very long time. Every Wednesday we would drive to his house in Taroona, and walk up the big hill to the house, often passing his wife, Isa, in the garden. Into the house and more stairs, and up to a living room that was big enough to fit two baby Steinway grand pianos side by side – one for the student and one for the teacher. 

I am not a great pianist, but I love to play, and music is a big part of my life in many ways. I wanted to reflect on Mr Mitchell’s influence on my appreciation of music, and how it connects to my work.

We learnt piano through a version of the [Suzuki Method](https://en.wikipedia.org/wiki/Suzuki_method), of which Mr Mitchell was an early pioneer of in Australia. This meant I never sat exams, but I was exposed to a huge amount of music, both in terms of listening and reading. As a child I would go to sleep while listening to tape recordings of the music I was learning. As I progressed, I would learn two or three pieces at a time, from a range of periods (e.g. Bach, Mozart, and Chopin). We never really spent any more than four or five weeks on any one piece. So I was exposed to a lot of music, and learnt to read music relatively efficiently. And because of that, I love to read music. Even now, two decades later, I really enjoy sitting down and try to play a piece I’ve never played before. 

Why do I love to read music? I like finding patterns, recognizing what chord progressions are likely given the key, appreciating and navigating the key changes, becoming familiar with the theme as it returns with variations. A lot of music is patterns and structures; certain chord progressions–elements of a song–that our ears find pleasant and familiar. But then music is so much more than that, too–every period, every composer, has their own style and interpretation. A mordent is played differently in a Baroque piece, compared with a Romantic-period piece, for example. 

On reflection, there are strong parallels between reading music and analysing a dataset in a statistical way, which is much of what I do in my research. When we analyze a dataset we look for patterns and find structures that we can account for to better understand broad trends and relationships. But not every population, not every sample, is the same. It is the surprising things, the anomalies, that keep us asking interesting questions. This approach of recognizing patterns, but acknowledging and understanding differences, is similar to the approach to reading music. It is not clear to me what the causal direction is here–am I good at reading music because I’m good at seeing patterns, or do I like analyzing data because I had that music training–but it’s clear these two interests are interconnected. 

Mr Mitchell’s approach to teaching was to encourage a holistic appreciation of music. He was excitable and bursting with enthusiasm–when we arrived for the lesson he would often have music blasting as we walked up the stairs, and we would find him dancing away as we entered the room. Sometimes when I was reciting a piece he could not help himself but to sit down and play along. When I played a piece well, he would scrawl encouraging words over the page with his fountain pen. And this enthusiasm was infectious. The music community was a big part of my life through high school and undergrad, many of my closest friendships are from playing in bands and musicals. 

Nowadays, my aforementioned ability to read has made it possible for me to hack through a few tunes accompanying a friend in Toronto, who is a professional singer. I enjoy talking about music with people and discovering new artists from friends. Of course, this appreciation is not just because of Mr Mitchell–I also had a great [flute teacher](https://www.tmta.com.au/Sys/PublicProfile/63081379), went to a [high school](https://clarencehigh.education.tas.edu.au/) with an excellent bands program, and am lucky to have my brothers and Mum and Dad who all love music (of all sorts). But Mr Mitchell gave me the tools and encouragement to foster a love of music I have carried through my life. As Rohan and I share music with our children, Mr Mitchell’s influence spans not decades, but generations.
